module.exports = {
    groups: {
        traveler: [1,2,3,4,30,40,63,64,78,84,86,104,107,118],
        activities: [26,28,29,31,32,39,48,56,57,58,64,66,68,76,77,78,79,83,84,95,96,98,100,105,115,116],
        food: [27,30,54,55,67,70,86,89,91,106,108,113,120],
        stats: [5,7,8,11,12,16,17,18,19,22,38,46,47,48,51,52,53,65,69,73,74,87,89,90,91,93,101,103,105,112],
        appearance: [6,9,10,20,21,23,34,35,36,37,43,44,45,46,47,49,50,59,60,81,82],
        talents: [13,14,15,25,61,65,75,93,99,102,109,114,117,119,121],
        possessions: [33,62,71,72,85,92,94,97,110,111],
        random: [41,42,80,88,122,123,124,125,126,127],
        favorites: [22,75,79,90,98,112,116]
    },
    picks: [
        { title: "World Traveler", description: "has visited the most countries", index: 1 },
        { title: "Ohio Traveler", description: "has most recently visted a different city than they live in from this list: Columbus, Cincinnati, Cleveland", index: 2 },
        { title: "State Traveler", description: "has most recently visited a different state", index: 3 },
        { title: "Islander", description: "has most recently visited an island", index: 4 },
        { title: "Breakable", description: "has broken the most bones", index: 5 },
        { title: "Listener", description: "has the biggest ears", index: 6 },
        { title: "Brushable", description: "has had the fewest cavities", index: 7 },
        { title: "Most Siblings", description: "has the most siblings", index: 8 },
        { title: "Shortest", description: "is the shortest", index: 9 },
        { title: "Tallest", description: "is the tallest", index: 10 },
        { title: "Oldest", description: "is the oldest", index: 11 },
        { title: "Youngest", description: "is the youngest", index: 12 },
        { title: "Booming Voice", description: "has the loudest voice", index: 13 },
        { title: "Booming Whistle", description: "can whistle the loudest", index: 14 },
        { title: "Linguist", description: "speaks the most languages", index: 15 },
        { title: "Birthday", description: "has their birthday next", index: 16 },
        { title: "Stencilocity", description: "has a the street address with the largest number", index: 17 },
        { title: "Steady", description: "has the biggest shoe size", index: 18 },
        { title: "Palmer", description: "has the largest palm", index: 19 },
        { title: "Hairy", description: "has the most body hair", index: 20 },
        { title: "Dotty", description: "has the most freckles", index: 21 },
        { title: "Dotty", description: "has the most dots from i's or j's in their full name", index: 22 },
        { title: "Dexterity Jones", description: "has the smallest hands", index: 23 },
        { title: "Form Stretcher", description: "has the most letters in their first and last names combined", index: 24 },
        { title: "Travolta", description: "best imitates John Travolta", index: 25 },
        { title: "Turkey", description: "most recently bowled", index: 26 },
        { title: "Chocobean", description: "most recently drank chocolate milk", index: 27 },
        { title: "Qat", description: "most recently played scrabble", index: 28 },
        { title: "Biker", description: "most recently rode a bicycle", index: 29 },
        { title: "Guzzler", description: "most recently went to a fast food restaurant", index: 30 },
        { title: "Purrfection", description: "most recently pet a cat", index: 31 },
        { title: "Beasties", description: "most recently pet a dog", index: 32 },
        { title: "Minicar", description: "drives the smallest car", index: 33 },
        { title: "Curly", description: "has the curliest hair", index: 34 },
        { title: "Blondie", description: "has the lightest colored hair", index: 35 },
        { title: "Face Sweater", description: "has the most facial hair", index: 36 },
        { title: "Don't Care", description: "has the longest hair", index: 37 },
        { title: "Bit Saver", description: "has the shortest email address", index: 38 },
        { title: "Eh?", description: "most recently heard live music", index: 39 },
        { title: "Beach Bum", description: "most recently went to a beach", index: 40 },
        { title: "Lefty", description: "is directly on my left", index: 41 },
        { title: "Righty", description: "is directly on my right", index: 42 },
        { title: "Traveling Light", description: "is wearing the fewest articles of clothing", index: 43 },
        { title: "Adorned", description: "is wearing the most jewelry", index: 44 },
        { title: "Green Man", description: "is wearing the most green", index: 45 },
        { title: "Holey Skin", description: "has the most pierced body parts", index: 46 },
        { title: "Tatoo Many", description: "has the most tatoos", index: 47 },
        { title: "Stench Free", description: "most recently took a bath or shower", index: 48 },
        { title: "Buttoned", description: "has the most buttons", index: 49 },
        { title: "Unbuttoned", description: "has the most unbuttoned buttons", index: 50 },
        { title: "Native", description: "was born the closest geographically", index: 51 },
        { title: "Only Child", description: "has the fewest number of siblings", index: 52 },
        { title: "Last in Line", description: "is last alphabetically by the second letter in your first name", index: 53 },
        { title: "V8 Lite", description: "most recently consumed Tomato Juice", index: 54 },
        { title: "Sea Breath", description: "most recently ate seafood", index: 55 },
        { title: "King Saver", description: "most recently played chess", index: 56 },
        { title: "Wedding Crasher", description: "most recently attended a wedding", index: 57 },
        { title: "Cozy", description: "most recently finished reading a novel", index: 58 },
        { title: "Pockets", description: "has the most pockets", index: 59 },
        { title: "Big Belt", description: "has the longest belt", index: 60 },
        { title: "Wrassler", description: "can come up with the best wrestler name", index: 61 },
        { title: "Keyed In", description: "has the most keys", index: 62 },
        { title: "Santa's Helper", description: "has been the closest to the North Pole", index: 63 },
        { title: "Scurvy Dog", description: "has spent the most nights on a boat", index: 64 },
        { title: "Critical Condition", description: "has had the longest stay in a hospital", index: 65 },
        { title: "Relaxed", description: "most recently did yoga", index: 66 },
        { title: "Cold Milk", description: "most recently ate ice cream", index: 67 },
        { title: "Good Kid", description: "most recently talked to their mother", index: 68 },
        { title: "Vowel Renwel", description: "has the longest non-vowel chunk in their full name", index: 69 },
        { title: "Parched", description: "is the thirstiest", index: 70 },
        { title: "Oldie", description: "drives the oldest car", index: 71 },
        { title: "Phat Whip", description: "drives the newest car", index: 72 },
        { title: "That's Sick!", description: "most recently was sick", index: 73 },
        { title: "Everyone Does It", description: "most recently pooped", index: 74 },
        { title: "Timer", description: "can guess the closest to the current time without looking", index: 75 },
        { title: "Kung Pow", description: "who most recently saw a Kung Fu Movie", index: 76 },
        { title: "Westerner", description: "who most recently saw a Western Movie", index: 77 },
        { title: "Yay Sports!", description: "who most recently attended a live sporting event", index: 78 },
        { title: "Hank You", description: "who most recently saw a movie starring Tom Hanks", index: 79 },
        { title: "Finger Game", description: "wins this game.  Everyone puts a fist in the middle.  On the count of 3, everyone puts out 1 or 0 fingers.  Number is fingers is how many people to the left of me starts", index: 80 },
        { title: "Trucker", description: "would look best with a trucker mustache", index: 81 },
        { title: "Elf", description: "has the pointest ears", index: 82 },
        { title: "Elf", description: "most recently saw the movie Elf", index: 83 },
        { title: "History Buff", description: "most recently went to a museum", index: 84 },
        { title: "Spare Some Change", description: "has the most change in their pocket/wallet/purse", index: 85 },
        { title: "Canadian", description: "most recently wen to Tim Hortons", index: 86 },
        { title: "Veteren", description: "has been on Facebook the longest", index: 87 },
        { title: "Catlike", description: "is the next person to meow", index: 88 },
        { title: "Baby Trees", description: "most recently ate broccolli", index: 89 },
        { title: "Big Fan", description: "has seen the most famous person", index: 90 },
        { title: "Achoo!", description: "is allergic to the most things", index: 91 },
        { title: "Got the Beats", description: "has the best ringtone", index: 92 },
        { title: "You Big Baby!", description: "is the biggest baby", index: 93 },
        { title: "Oldie but a Goodie", description: "owns the oldest thing", index: 94 },
        { title: "Green Thumb", description: "most recently planted something", index: 95 },
        { title: "Stench Free", description: "most recently did their laundry", index: 96 },
        { title: "Pockets", description: "has the most things in their pockets", index: 97 },
        { title: "Public Pooper", description: "most recently pooped in a public place", index: 98 },
        { title: "The Frizzler", description: "can think of the best new place for the magic school bus to go", index: 99 },
        { title: "Black Eye Peas", description: "most recently heard to a song by The Black Eyed Peas", index: 100 },
        { title: "Early Riser", description: "got up earliest this morning", index: 101 },
        { title: "Evil Genius", description: "has the best maniacal laugh", index: 102 },
        { title: "Water Dweller", description: "lives the closest to a body of water", index: 103 },
        { title: "Cruiser", description: "most recently went on a cruise", index: 104 },
        { title: "Shears", description: "most recently had a hair cut", index: 105 },
        { title: "Squirrely", description: "most recently ate nuts", index: 106 },
        { title: "Sandy", description: "most recently put their feet in sand", index: 107 },
        { title: "Fun Guy", description: "most recently ate a mushroom", index: 108 },
        { title: "Guru", description: "is the wisest", index: 109 },
        { title: "Cowboy", description: "has the largest cowboy boots", index: 110 },
        { title: "Facade", description: "has the coolest mask", index: 111 },
        { title: "Late Sleeper", description: "has their alarm set for the latest time", index: 112 },
        { title: "Olympian", description: "most recently ate Greek food", index: 113 },
        { title: "Compass", description: "(after closing your eyes) points most accurately to north", index: 114 },
        { title: "Springfieldian", description: "most recently saw an episode of The Simpsons", index: 115 },
        { title: "Brave Petter", description: "most recently touched an animal that wasn't a pet", index: 116 },
        { title: "Australian", description: "thinks they know the most about Australia", index: 117 },
        { title: "Royalty", description: "most recently visited a castle", index: 118 },
        { title: "Humm Bug", description: "can hum the highest note", index: 119 },
        { title: "Tiki Tidbit", description: "most recently ate pineapple", index: 120 },
        { title: "Astonomer", description: "can name the most moons of Jupiter", index: 121 },
        { title: "Shooter", description: "wins this game. On the count of 3, everyone makes a finger gun at somebody else. The person shot the most goes first.", index: 122 },
        { title: "Shooter", description: "wins this game. On the count of 3, everyone makes a finger gun at yourself, somebody else, or in the air. Any person shot is out, except if you also shot yourself. Continue until only one person remains.", index: 123 },
        { title: "Unique", description: "wins this game. On the count of 3, everyone throws out a number of fingers (1-5). Lowest unique number goes first.", index: 124 },
        { title: "Chwazi", description: "the Chwazi app picks", index: 125 },
        { title: "Piece Meal", description: "gets their token pulled out of my pocket.", index: 126 },
        { title: "Color Carefree", description: "picked their color last", index: 127 }
    ]
};
